[workspace]
members = ["protocol_codegen"]

[package]
name = "kafka_protocol"
version = "0.1.0"
authors = [
    "Diggory Blake <diggsey@googlemail.com>",
    "Jem McElwain <jem.xyz@pm.me>",
]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
bytes = "1.0.1"
uuid = "0.8.2"
log = "0.4.14"
indexmap = "1.7.0"
env_logger = "0.8.4"
crc = "2.0.0"
snap = "1.0.5"
flate2 = "1.0.20"
string = { version = "0.3.0", git = "https://github.com/0x1991babe/string.git" }