[workspace]
members = ["franz_protocol", "xtask"]
# exclude = ["xtask"]

[package]
name = "franz"
version = "0.1.0"
authors = ["Diggory Blake <diggsey@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.11", features = ["tcp", "io-util", "sync", "time", "rt-core", "stream", "macros"] }
tokio-util = { version = "0.2.0", features = ["codec"] }
bytes = "0.5.4"
uuid = "0.8.1"
log = "0.4.8"
futures = "0.3.4"
async-trait = "0.1.24"
chashmap = "2.2.2"
franz_protocol = { version = "0.1", path = "franz_protocol" }
indexmap = "1.3.2"
env_logger = "0.7.1"

[build-dependencies]
async-trait = "0.1.24"

[patch.crates-io]
bytes = { git = "https://github.com/Diggsey/bytes.git", branch = "try_get" }
